---
- hosts: all
  tasks:
    - name: Add apt key
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
      become: true

    - name: Add postgresql repo
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
        state: present
        filename: pgdg
      become: true

    - name: Update apt cache
      apt:
        name: postgresql-8.4
        update_cache: yes
      become: true
